# Generated by Django 5.1.2 on 2024-10-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stockdata_close_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('predicted_price', models.FloatField()),
            ],
        ),
    ]
